//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gigashop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public int BlogID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
